#!/usr/bin/env ruby

$LOAD_PATH.unshift File.expand_path('../../lib', __FILE__)
require "creation"

# templates_root = File.expand_path(File.join("..", "templates"), File.dirname(__FILE__))
# Creation::Generators::AppGenerator.source_root templates_root
# Creation::Generators::AppGenerator.source_paths << Rails::Generators::AppGenerator.source_root << templates_root

# Creation::Generators::AppGenerator.start
args = Rails::Generators::ARGVScrubber.new(ARGV).prepare!
Creation::Generators::AppGenerator.start args
