#!/usr/bin/env ruby

$LOAD_PATH.unshift File.expand_path('../../lib', __FILE__)
require "creation"

args = Rails::Generators::ARGVScrubber.new(ARGV).prepare!
Creation::Generators::AppGenerator.start args
